version: '3'
services:
#mssql docker
  tactaintershipproject-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Konjic1981
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - tactaintershipprojectnet2023

  tactaintershipproject-api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings:DefaultConnection=Server=tactaintershipproject-sql,1433;Database=TactaIntershipProject;User=sa;Password=Konjic1981;ConnectRetryCount=0;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 7037:7037
    networks:
      - tactaintershipprojectnet2023
    links:
      - tactaintershipproject-sql
    depends_on:
      - tactaintershipproject-sql
      
networks:
  tactaintershipprojectnet2023:
    driver: bridge   