// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TactaIntershipProject.Service.Database;

#nullable disable

namespace TactaIntershipProject.Service.Migrations
{
    [DbContext(typeof(TactaIntershipProjectContext))]
    partial class TactaIntershipProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TactaIntershipProject.Service.Database.Items", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            ItemName = "item1"
                        },
                        new
                        {
                            ItemId = 2,
                            ItemName = "item2"
                        },
                        new
                        {
                            ItemId = 3,
                            ItemName = "item3"
                        },
                        new
                        {
                            ItemId = 4,
                            ItemName = "item4"
                        },
                        new
                        {
                            ItemId = 5,
                            ItemName = "item5"
                        });
                });

            modelBuilder.Entity("TactaIntershipProject.Service.Database.Shoppers", b =>
                {
                    b.Property<int>("ShopperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShopperId"));

                    b.Property<string>("ShopperName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShopperId");

                    b.ToTable("Shoppers");

                    b.HasData(
                        new
                        {
                            ShopperId = 1,
                            ShopperName = "shopper1"
                        },
                        new
                        {
                            ShopperId = 2,
                            ShopperName = "shopper2"
                        },
                        new
                        {
                            ShopperId = 3,
                            ShopperName = "shopper3"
                        },
                        new
                        {
                            ShopperId = 4,
                            ShopperName = "shopper4"
                        },
                        new
                        {
                            ShopperId = 5,
                            ShopperName = "shopper5"
                        });
                });

            modelBuilder.Entity("TactaIntershipProject.Service.Database.ShoppingList", b =>
                {
                    b.Property<int>("ShoppingListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoppingListId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("ShopperId")
                        .HasColumnType("int");

                    b.HasKey("ShoppingListId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ShopperId");

                    b.ToTable("ShoppingLists");

                    b.HasData(
                        new
                        {
                            ShoppingListId = 1,
                            ItemId = 2,
                            ShopperId = 1
                        },
                        new
                        {
                            ShoppingListId = 2,
                            ItemId = 1,
                            ShopperId = 3
                        },
                        new
                        {
                            ShoppingListId = 3,
                            ItemId = 5,
                            ShopperId = 4
                        });
                });

            modelBuilder.Entity("TactaIntershipProject.Service.Database.ShoppingList", b =>
                {
                    b.HasOne("TactaIntershipProject.Service.Database.Items", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TactaIntershipProject.Service.Database.Shoppers", "Shopper")
                        .WithMany()
                        .HasForeignKey("ShopperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Shopper");
                });
#pragma warning restore 612, 618
        }
    }
}
